"""Narrow effects required by story lifecycle and creation use cases."""
from dataclasses import dataclass
from typing import Any, Callable, Awaitable, Protocol, AsyncContextManager
from mrp.shared.models import SessionState

class LifecycleRepository(Protocol):
    def story_for(self,branch_id:str)->str: ...
    def membership(self,story_id:str)->str: ...
    def require_unlocked(self,story_id:str)->None: ...
    def normalize_story(self,story_id:str)->None: ...
    def reserve(self,operation_id:str,action:str,scope:str,payload:dict)->dict|None: ...
    def commit(self,operation_id:str,action:str,story_id:str,**kwargs)->dict: ...
    def trash(self,story_id=None,generation_id=None): ...
    def known_trash_stories(self)->set[str]: ...
    def recover_cutovers(self)->None: ...
    def recover_operations(self)->None: ...
    def reject_operation(self,operation_id:str,error:Exception)->None: ...
    def report_delivery(self,operation_id:str,pending:bool,error:Exception|None=None)->dict: ...
    def conflict(self,message:str,code:str='lifecycle_conflict',status_code:int=409)->Exception: ...

@dataclass(frozen=True)
class LifecyclePorts:
    repo: LifecycleRepository
    require_visible: Callable[[str],None]
    is_transactional: Callable[[str],bool]
    read_state: Callable[[str],Awaitable[SessionState|None]]
    reject_busy: Callable[[str],None]
    snapshot: Callable[...,Awaitable[dict]]
    preset: Callable[[str],dict|None]
    post_commit: Callable[[str,str,dict],Awaitable[None]]
    cleanup_purges: Callable[[],None]
    adopt_legacy_trash: Callable[[str],Awaitable[None]]
    diagnostic: Callable[[str,Exception],None]

class CreationExecute(Protocol):
    async def __call__(self,action:str,payload:dict,operation:str|None,create:Callable[[],Awaitable[dict]],response_meta:dict|None,gate:Callable[[],AsyncContextManager[None]])->dict: ...

class PublicationGate(Protocol):
    def __call__(self,action:str,payload:dict)->AsyncContextManager[None]: ...

@dataclass(frozen=True)
class CreationPorts:
    execute: CreationExecute
    publication_gate: PublicationGate
