"""Narrow capabilities consumed by story applications.

Infrastructure adapters implement these contracts; applications cannot discover
repositories, providers, SQLite connections or arbitrary container services.
"""
from __future__ import annotations
from collections.abc import Awaitable, Callable, Coroutine
from contextlib import AbstractAsyncContextManager, AbstractContextManager
from typing import Protocol, TypedDict
import asyncio
from mrp.shared.models import SessionState, MemoryRecord, Scene, Message, TurnRun, DirectorDecision, GroupActor, Lorebook

JSON = str | int | float | bool | None | list['JSON'] | dict[str, 'JSON']
Payload = dict[str, JSON]

class Receipt(TypedDict):
    fingerprint: str
    result: JSON
    revision: int

class MemoryJob(TypedDict):
    fingerprint: str
    status: str
    plan: Payload
    result: Payload | None
    new: bool

class RuntimePort(Protocol):
    turn_lock: AbstractAsyncContextManager
    consolidation_lock: asyncio.Lock
    active_turn_run_id: str | None
    active_conversation_run_id: str | None
    turn_checkpoint_active: bool

class BranchRunner(Protocol):
    """Only the mutable staged runtime used by these application use cases."""
    state: SessionState
    runtime: RuntimePort
    lorebooks: list[Lorebook]
    _committed_state: SessionState
    _branch_committed_state: SessionState
    def busy(self) -> bool: ...
    async def _emit(self, event: str, payload: Payload, *, lossy: bool = False) -> None: ...

class CommandRepositoryPort(Protocol):
    async def lookup_command(self, branch: str, operation: str) -> Receipt | None: ...
    async def lookup_generation(self, branch: str, operation: str) -> str | None: ...
    async def lookup_memory_job(self, branch: str, operation: str) -> MemoryJob | None: ...
    async def reserve_generation(self, branch: str, operation: str, fingerprint: str) -> None: ...

class StagedCommit(Protocol):
    state: SessionState
    expected_revision: int
    commit_operation_id: str
    commit_events: list[tuple[str, Payload, bool]]
    memory_actions: list[Payload]
    command_receipt: Payload | None

class BranchCommitPort(CommandRepositoryPort, Protocol):
    async def require_visible(self, branch: str) -> None: ...
    def branch_gate(self, branch: str) -> AbstractAsyncContextManager: ...
    async def load_committed(self, branch: str) -> SessionState | None: ...
    async def atomic_memory(self, runner: BranchRunner) -> bool: ...
    async def prepare_legacy_memory(self, runner: BranchRunner, operation: str) -> bool: ...
    async def finish_legacy_memory(self, runner: BranchRunner, operation: str, *, rollback: bool = False) -> None: ...
    async def persist(self, staged: StagedCommit) -> None: ...
    async def refresh_mirrors(self, branch: str, actors: set[str]) -> None: ...
    async def uses_outbox(self, branch: str) -> bool: ...
    async def dispatch_outbox(self, runner: BranchRunner, revision: int) -> None: ...

class MemoryRepositoryPort(CommandRepositoryPort, Protocol):
    def consolidation_enabled(self) -> bool: ...
    def branch_gate(self, branch: str) -> AbstractAsyncContextManager: ...
    async def ensure_transactional(self, branch: str) -> None: ...
    async def prepare_records(self, records: list[MemoryRecord]) -> list[Payload]: ...
    async def record_by_id(self, record: str) -> MemoryRecord | None: ...
    async def branch_actor_ids(self, branch: str) -> list[str]: ...
    async def plan_next_window(self, actor: str, branch: str, turn: int, *, retry_failed: bool) -> tuple[int, int, bool]: ...
    async def window_rows(self, actor: str, branch: str) -> list[Payload]: ...
    async def last_consolidated_turn(self, actor: str, branch: str) -> int: ...
    async def claim_memory_job(self, branch: str, operation: str, fingerprint: str, plan: Payload) -> MemoryJob: ...
    async def current_watermark(self, branch: str) -> int: ...
    async def records_for(self, actor: str, branch: str) -> list[MemoryRecord]: ...

class BackgroundRuntimePort(Protocol):
    def branch_lease(self, branch: str) -> AbstractContextManager: ...
    def spawn(self, runner: BranchRunner, work: Coroutine[object, object, JSON | None]) -> asyncio.Task | None: ...

class MemoryGenerationPort(Protocol):
    async def generate_window(self, runner: BranchRunner, snapshot: SessionState, actor: str, start: int, end: int) -> list[MemoryRecord]: ...
    async def generate_scene(self, runner: BranchRunner, snapshot: SessionState, actor: str, scene: Scene) -> MemoryRecord | None: ...

class DirectorCheckpointPort(Protocol):
    def pending(self, runner: BranchRunner) -> DirectorDecision | None: ...
    async def resolve(self, runner: BranchRunner, accept: bool) -> Payload | None: ...
    async def resolve_legacy(self, runner: BranchRunner, accept: bool) -> list[Message]: ...
    def find(self, runner: BranchRunner, operation: str) -> TurnRun: ...
    def response(self, runner: BranchRunner, run: TurnRun) -> Payload: ...

class RegenerationInput(Protocol):
    operation_id: str
    expected_branch_revision: int
    expected_fingerprint: str
    expected_player_identity_id: str | None

class StoryGenerationPort(Protocol):
    async def referenced_by_child(self, branch: str, messages: set[str]) -> bool: ...
    async def regenerate(self, runner: BranchRunner, action: str, message: str, request: RegenerationInput, *, protect: Callable[[set[str]], Awaitable[None]], variant_index: int | None, baseline_transform: Callable | None) -> Payload: ...
    async def generate_group(self, runner: BranchRunner, group: GroupActor, operation: str) -> Message: ...
    def install_message(self, runner: BranchRunner, draft: Message) -> None: ...
