/** In-memory API contracts for the third-round production React acceptance.
 * No disk storage, proxy, model provider, private content or live application is used.
 * Mutable resources and request journals let tests distinguish a rendered draft from a commit/readback.
 */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';

export function roundThreeFixture({ characters, worlds, designBooks, snapshot, stamp, json }) {
  const clone = value => structuredClone(value);
  const state = { requests: [], writes: [], failBookSave: false, failScenarioSave: false, failGeneration: false, failDraftSave: false, failCommit: false, delay: 1100, holdAgentRead: false, pendingAgentReads: [] };
  const entry = (uid, patch = {}) => ({ uid, keys: [`灯塔${uid}`, '沿岸'], secondary_keys: ['夜晚'], content: `合成沿岸档案 ${uid}，供正文和全字段验收。\n地图与灯塔的细节只属于验收场景。`, comment: `沿岸记录 ${uid}`, enabled: uid % 5 !== 0, constant: uid % 7 === 0, selective: uid % 3 === 0, selective_logic: 3, order: uid + 80, anchor: uid % 2 ? 'near' : 'at_depth', depth: 4, probability: 90, extensions: { 'synthetic.extra': { preserved: true } }, ...patch });
  const card = (name = '合成候选记录者') => ({ ...clone(characters[0].card), name, spec: 'chara_card_v2', spec_version: '2.0', creator: '合成作者', character_version: '1.0', creator_notes: '验收角色，不含私人素材。', alternate_greetings: ['另一句合成开场。'], first_mes: '灯塔上的灯亮起来了。', mes_example: '{{user}}: 你看到了什么？\n{{char}}: 那张旧地图。', system_prompt: '合成人设提示。', post_history_instructions: '合成历史提示。', avatar_path: null, source_format: 'ccv2' });
  Object.assign(characters[0], { aliases: ['星灯记录者'], source_world_id: worlds[0].id, llm: { model: 'example/model', base_url: '', inherit_model: true, inherit_base_url: true, sampling: { max_tokens: 0 } } });
  Object.assign(characters[0].card, card('向导1'));
  const archive = { id: 'archive-round3', kind: 'background', subtype: 'general', title: '潮汐灯塔', aliases: [], tags: ['沿岸'], summary: '第二版档案摘要：灯塔在涨潮后亮起。', body: '第二版完整档案：守望者按潮汐记录灯塔的亮灯时间。', visibility: 'public', kind_data: {}, schema_version: 1, revision: 3, created_at: stamp, updated_at: stamp };
  designBooks.splice(0, designBooks.length, ...Array.from({ length: 8 }, (_, index) => ({ id: index ? `book-round3-${index}` : 'book-design', name: index ? `合成世界书 ${index + 1}` : '灯塔与潮汐', description: '第三轮真实 React 的合成世界书正文。', revision: 1, created_at: stamp, updated_at: `2026-01-01T12:00:${String(30-index).padStart(2,'0')}Z`, tags: index % 2 ? ['航海'] : ['合成'], scan_depth: 4, token_budget: 1000, recursive_scanning: false, source_format: 'st', entries: Array.from({ length: index ? 3 : 43 }, (_, n) => entry(n+1, n===0 && index===0 ? { extensions: { 'synthetic.extra': { preserved: true }, 'mrp.archive_source': { world_id: worlds[0].id, archive_id: archive.id, archive_revision: 1 } } } : {})) })));
  const owners = Object.fromEntries(designBooks.filter((_, index) => index < 6).map((book, index) => [book.id, { world_id: worlds[index % 2].id, world_title: worlds[index % 2].title }]));
  const worldDetail = world => ({ ...world, archived: false, core_brief: '用于验收的合成世界核心设定。', runtime_policy: 'compiled', schema_version: 1, archive_records: world.id === worlds[0].id ? [clone(archive)] : [], lorebook_ids: Object.entries(owners).filter(([, owner])=>owner.world_id===world.id).map(([id])=>id), tags: ['合成'], lorebook_count: Object.values(owners).filter(owner=>owner.world_id===world.id).length });
  const scenarios = [];
  const scenarioFromInput = (input, id) => ({ id, package_id: id, format: 'mrp.scenario', format_version: 1, schema_version: 1, revision: 1, title: input.title, description: input.description || '', author: input.author || '', license: input.license || '', source_url: input.source_url || '', tags: input.tags || [], player_persona: input.player_persona || '', instructions: input.instructions || '', cast: (input.character_ids || ['char-demo0']).map((id,n)=>({ key: `cast-${n}`, source_asset_id: id, source_asset_revision: characters.find(c=>c.id===id)?.revision || 1, card: clone(characters.find(c=>c.id===id)?.card || characters[0].card), aliases: [], talkativeness: .5, interject_enabled: false, followup_enabled: false, lorebook_keys: [] })), lorebooks: (input.lorebook_ids || []).map((id,n)=>({ ...clone(designBooks.find(book=>book.id===id) || designBooks[0]), key: `book-${n}`, source_asset_id: id, source_asset_revision: designBooks.find(book=>book.id===id)?.revision || 1 })), opening: input.opening || { location: '灯塔前庭', description: '合成开场场景', narration: '海面上的灯光亮了。', member_keys: [] }, play: input.play || { narrative_pov: null, narrative_density: null, director_mode: null }, components: input.world_id ? { world: { kind: 'world', schema_version: 1, revision: 1, payload: worldDetail(worlds.find(world=>world.id===input.world_id) || worlds[0]), extensions: {} } } : {}, created_at: stamp, updated_at: stamp, imported_at: null });
  scenarios.push(scenarioFromInput({title:'合成灯塔预设',description:'真实页面使用的隔离预设。',character_ids:['char-demo0','char-demo1'],lorebook_ids:['book-design'],tags:['合成'],world_id:worlds[0].id},'scenario-round3'));
  const inspirationDraft = (id='inspiration-draft-round3') => ({ id, revision: 1, status: 'review', payload: card('合成灵感记录者'), aliases: ['合成别名'], field_history: [], quality_review: { passed: true, issues: [], note: '合成质量检查，不能证明真实模型质量。' }, committed_character_id: null });
  const inspirationJobs = [{ id:'inspiration-round3', search_query:'灯塔', requirement:'合成灵感审阅任务', detail:'只使用合成参考。', borrow:'开场节奏', avoid:'照搬正文', status:'review', stage:'审阅', drafts:[inspirationDraft()], errors:[], attempt:1, brief_revision:1, agent_enabled:true, agent_messages:[], created_at:stamp, updated_at:stamp, references:[] }, { id:'inspiration-failed-round3', search_query:'', requirement:'合成失败任务', detail:'保留输入', borrow:'', avoid:'', status:'failed', stage:'生成', drafts:[], errors:['合成生成失败，可手动重试。'], attempt:1, brief_revision:1, agent_enabled:false, agent_messages:[], created_at:stamp, updated_at:stamp, references:[] }];
  const importDraft = (kind, id, payload) => ({ id, kind, title: kind === 'character' ? '合成导入人物' : `合成${kind}草稿`, payload: payload || (kind==='character' ? card('合成导入人物') : clone(archive)), status:'needs_review', error:'', warnings:['这是合成审阅依据。'], evidence:'来源原稿：合成灯塔记录者。', source_start:0, source_end:12, schema_fingerprint:'round3-synthetic', world_id: kind==='character' ? null : worlds[0].id, target_asset_id:null, target_revision:null, revision:1, saved_asset_id:null, source_exact:true, selected_fields:null });
  const importJobs = [{ id:'job-round3', title:'合成导入审阅任务', status:'needs_review', target_kind:null, world_id:null, source_length:30, candidates:[{kind:'character',title:'合成导入人物',excerpt:'原稿节选'},{kind:'background',title:'合成背景',excerpt:'背景节选'}], drafts:[importDraft('character','draft-character-round3'),importDraft('background','draft-background-round3'),importDraft('biology','draft-biology-round3')], errors:[], created_at:stamp, updated_at:stamp }, {id:'job-failed-round3',title:'合成失败导入',status:'failed',target_kind:'character',world_id:null,source_length:8,candidates:[],drafts:[],errors:['合成错误，重试保留原稿'],created_at:stamp,updated_at:stamp}];
  const sources = { world_id: worlds[0].id, world_title: worlds[0].title, world_revision:1, source_changed:false, sources:[{id:archive.id,kind:archive.kind,title:archive.title,revision:3,char_count:archive.body.length,excerpt:archive.summary,content:archive.body}] };
  const agentDraft = { id:'agent-draft-round3',revision:1,status:'review',edited:false,payload:entry(1),source_refs:[{source_id:archive.id,quote:'守望者按潮汐记录'}],positive_examples:['灯塔亮了'],negative_examples:['去山里'],rationale:'合成触发说明',risk_notes:[],validation_errors:[] };
  const agentJobs = [{id:'agent-round3',world_id:worlds[0].id,world_title:worlds[0].title,world_revision:1,target_lorebook_id:null,target_revision:null,new_lorebook_name:'合成Agent书',goal:'合成整理任务',status:'review',stage:'审阅',drafts:[clone(agentDraft)],errors:[],source_ids:[archive.id],source_changed:false,progress:{tool_calls:2,last_tool:'完成',attempt:1},created_at:stamp,updated_at:stamp}];
  const createCharacter = payload => { const next={...clone(characters[0]),id:`char-round3-${characters.length}`,revision:1,card:clone(payload),aliases:[],source_world_id:null}; characters.push(next); return next; };
  const simulation = {positive:[{text:'灯塔亮了',triggered:true}],negative:[{text:'去山里',triggered:false}],estimated_tokens:32,valid:true};
  const sleep = () => new Promise(done=>setTimeout(done,state.delay));
  async function body(req) { let raw=''; for await(const chunk of req) raw+=chunk; return raw ? JSON.parse(raw) : {}; }
  function record(req,path,value) { const item={method:req.method,path,body:clone(value),operationId:req.headers['x-operation-id']||null}; state.writes.push(item); return item; }
  const reject = (res,message,code=503) => { json(res,{detail:message},code); return true; };
  const send = (res,value) => { json(res,clone(value)); return true; };
  async function route(req,res,path,url) {
    state.requests.push({method:req.method,path,query:url.search});
    const method=req.method;
    if(path==='/api/v1/worlds/lorebook-owners') return send(res,owners);
    if(/^\/api\/v1\/worlds\/world-demo\d+$/.test(path) && method==='GET') { const world=worlds.find(world=>world.id===path.split('/')[4]); return world ? send(res,worldDetail(world)) : reject(res,'合成世界不存在',404); }
    if(path==='/api/v1/characters/persona-preview') { const value=await body(req); return send(res,{persona:`人设预览\n${value.card?.name || ''}\n${value.card?.description || ''}`,tokens:64}); }
    if(path==='/api/v1/characters/preview-turn') { const value=await body(req); record(req,path,value); await sleep(); return send(res,{reply:`合成试聊：${value.message}`,tokens:12}); }
    if(path==='/api/v1/characters/ai-edit') { const value=await body(req); record(req,path,value); await sleep(); return state.failGeneration ? reject(res,'合成改写失败') : send(res,{value:`合成改写候选：${value.card?.[value.field] || ''}`,field:value.field}); }
    if(path==='/api/v1/characters/generate') { const value=await body(req); record(req,path,value); await sleep(); if(state.failGeneration) return reject(res,'合成角色生成失败'); return send(res,Array.from({length:value.count||3},(_,n)=>({card:card(`合成候选记录者 ${n+1}`),aliases:[`候选${n+1}`]}))); }
    if(path==='/api/v1/lorebooks/generate' || path==='/api/v1/lorebooks/generate/extend') { const value=await body(req); record(req,path,value); await sleep(); if(state.failGeneration) return reject(res,'合成世界书生成失败'); const entries=Array.from({length:value.count||4},(_,n)=>entry(n+1)); return send(res,path.endsWith('/extend') ? entries : {...clone(designBooks[0]),id:'generated-round3',name:`合成生成：${value.topic}`,entries}); }
    if(path==='/api/v1/lorebooks' && method==='GET') return send(res,designBooks);
    if((path==='/api/v1/lorebooks' || path==='/api/v1/lorebooks/blank') && method==='POST') { const value=await body(req); record(req,path,value); if(state.failBookSave) return reject(res,'合成世界书保存失败'); const next={...clone(designBooks[0]),...(value.book||value),id:`book-created-round3-${designBooks.length}`,revision:1,entries:value.book?.entries||[],created_at:stamp,updated_at:stamp}; designBooks.push(next); return send(res,next); }
    const bookMatch=path.match(/^\/api\/v1\/lorebooks\/([^/]+)(?:\/(copy))?$/);
    if(bookMatch) { const book=designBooks.find(book=>book.id===bookMatch[1]); if(!book) return reject(res,'合成世界书不存在',404); if(method==='GET') return send(res,book); const value=await body(req); record(req,path,value); if(state.failBookSave) return reject(res,'合成世界书保存失败'); if(method==='DELETE') { designBooks.splice(designBooks.indexOf(book),1); return send(res,{ok:true}); } if(bookMatch[2]==='copy') { const next={...clone(book),...value,id:`book-copy-round3-${designBooks.length}`,revision:1}; designBooks.push(next); return send(res,next); } if(value.expected_revision!==book.revision) return reject(res,'合成世界书版本冲突',409); Object.assign(book,value,{revision:book.revision+1}); return send(res,book); }
    if(path==='/api/v1/scenarios') { if(method==='GET') return send(res,scenarios.map(item=>({...item,character_names:item.cast.map(c=>c.card.name),lorebook_count:item.lorebooks.length}))); const value=await body(req); record(req,path,value); if(state.failScenarioSave) return reject(res,'合成场景预设保存失败'); assert.ok(value.title?.trim()); assert.ok(value.character_ids?.length); const next=scenarioFromInput(value,`scenario-created-${scenarios.length}`); scenarios.push(next); return send(res,next); }
    const scenarioMatch=path.match(/^\/api\/v1\/scenarios\/([^/]+)(?:\/(start|save-world))?$/);
    if(scenarioMatch) { const scenario=scenarios.find(item=>item.id===scenarioMatch[1]); if(!scenario) return reject(res,'合成场景不存在',404); if(method==='GET') return send(res,scenario); const value=await body(req); record(req,path,value); if(method==='DELETE') { scenarios.splice(scenarios.indexOf(scenario),1); return send(res,{ok:true}); } if(scenarioMatch[2]==='save-world') return send(res,worldDetail(worlds[0])); if(scenarioMatch[2]==='start') return send(res,{...snapshot,meta:{...snapshot.meta,title:scenario.title}}); }
    if(path==='/api/v1/card-sources') return send(res,[{source_id:'synthetic',label:'合成参考库',summary:'没有连接外站。',homepage:'',filters:[],paging:'offset',full_card:true}]);
    const hit={source_id:'synthetic',card_id:'card-reference',title:'合成参考记录者',creator:'合成作者',summary:'合成公开参考简介。',tags:['合成'],source_url:'',published_at:stamp,content_rating:'sfw',raw_metrics:{}};
    if(path==='/api/v1/card-searches' || path==='/api/v1/card-searches/next') { const value=await body(req); record(req,path,value); const page={source_id:'synthetic',status:'ok',results:[hit],next_cursor:null,error:null,skipped_count:0}; return send(res,path.endsWith('/next') ? page : {query:value.query,sources:[page]}); }
    if(path==='/api/v1/card-sources/synthetic/cards/card-reference') return send(res,{hit,card:card('合成参考记录者'),fetched_at:stamp,content_sha256:createHash('sha256').update('synthetic-reference').digest('hex')});
    if(path==='/api/v1/card-inspiration-jobs') { if(method==='GET') return send(res,inspirationJobs); const value=await body(req); record(req,path,value); const next={...clone(inspirationJobs[0]),...value,id:`inspiration-created-${inspirationJobs.length}`,drafts:[],status:'ready'}; inspirationJobs.unshift(next); return send(res,next); }
    const inspirationMatch=path.match(/^\/api\/v1\/card-inspiration-jobs\/([^/]+)(?:\/(generate|brief|agent\/turn|drafts\/([^/]+)(?:\/(commit))?))?$/);
    if(inspirationMatch) { const job=inspirationJobs.find(item=>item.id===inspirationMatch[1]); if(!job) return reject(res,'合成灵感任务不存在',404); if(method==='GET') return send(res,job); const value=await body(req); record(req,path,value); if(method==='DELETE') { inspirationJobs.splice(inspirationJobs.indexOf(job),1); return send(res,{ok:true}); } const action=inspirationMatch[2]; if(action==='generate') { await sleep(); if(state.failGeneration) return reject(res,'合成灵感生成失败'); job.status='review';job.drafts.push(inspirationDraft(`draft-${job.drafts.length}`));return send(res,job); } if(action==='brief') { assert.equal(value.expected_revision,job.brief_revision);Object.assign(job,value,{brief_revision:job.brief_revision+1});return send(res,job); } if(action==='agent/turn') {job.agent_messages.push({role:'user',content:value.message,created_at:stamp},{role:'assistant',content:'合成讨论建议，保留当前草稿。',created_at:stamp});return send(res,job); } const draft=job.drafts.find(item=>item.id===inspirationMatch[3]); if(!draft) return reject(res,'合成草稿不存在',404); assert.equal(value.expected_revision,draft.revision); if(state.failDraftSave) return reject(res,'合成草稿保存失败'); if(inspirationMatch[4]==='commit' && state.failCommit) return reject(res,'合成草稿入库失败'); Object.assign(draft,{payload:clone(value.payload),aliases:value.aliases||[],revision:draft.revision+1}); if(inspirationMatch[4]==='commit') {if(state.failCommit)return reject(res,'合成草稿入库失败');const character=createCharacter(draft.payload);draft.status='committed';draft.committed_character_id=character.id;return send(res,{character,draft});} return send(res,draft); }
    if(path==='/api/v1/asset-import-jobs') { if(method==='GET') return send(res,importJobs); const value=await body(req);record(req,path,value);const next={id:`job-created-${importJobs.length}`,title:'合成新导入任务',status:'ready',target_kind:value.target_kind||null,world_id:value.world_id||null,source_length:value.source?.length||0,source:value.source||'',candidates:[{kind:'character',title:'合成新人物',excerpt:'合成节选'}],drafts:[],errors:[],created_at:stamp,updated_at:stamp};importJobs.unshift(next);return send(res,next); }
    const importMatch=path.match(/^\/api\/v1\/asset-import-jobs\/([^/]+)(?:\/(source|analyze|candidates|generate|drafts\/([^/]+)(?:\/(commit|regenerate))?))?$/);
    if(importMatch) { const job=importJobs.find(item=>item.id===importMatch[1]);if(!job)return reject(res,'合成导入任务不存在',404);if(importMatch[2]==='source')return send(res,{source:job.source||'合成灯塔记录者。\n用于导入、审阅和来源对照。'});if(method==='GET')return send(res,job);const value=await body(req);record(req,path,value);if(method==='DELETE'){importJobs.splice(importJobs.indexOf(job),1);return send(res,{ok:true});}if(importMatch[2]==='candidates'){job.candidates=value.candidates;job.status='classified';return send(res,job);}if(importMatch[2]==='analyze'){job.status='classified';return send(res,job);}if(importMatch[2]==='generate'){await sleep();if(state.failGeneration)return reject(res,'合成导入生成失败');job.drafts=job.candidates.map((candidate,n)=>importDraft(candidate.kind,`generated-${n}`,undefined));job.status='needs_review';return send(res,job);}const draft=job.drafts.find(item=>item.id===importMatch[3]);if(!draft)return reject(res,'合成导入草稿不存在',404);if(importMatch[4]==='regenerate'){await sleep();draft.proposal={payload:{...clone(draft.payload),personality:'合成重新生成性格'},warnings:[],error:'',evidence:'合成候选'};return send(res,job);}if(importMatch[4]==='commit'){if(state.failCommit)return reject(res,'合成入库失败');draft.saved_asset_id=draft.kind==='character'?createCharacter(draft.payload).id:`archive-saved-${draft.id}`;draft.status='saved';draft.revision++;return send(res,draft);}assert.equal(value.expected_revision,draft.revision);if(state.failDraftSave)return reject(res,'合成导入草稿保存失败');Object.assign(draft,value,{revision:draft.revision+1});return send(res,draft); }
    if(path==='/api/v1/lorebook-agent-jobs') {if(method==='GET')return send(res,agentJobs);const value=await body(req);record(req,path,value);const next={...clone(agentJobs[0]),...value,id:`agent-created-${agentJobs.length}`,drafts:[clone(agentDraft)],status:'review'};agentJobs.unshift(next);return send(res,next);}
    const agentMatch=path.match(/^\/api\/v1\/lorebook-agent-jobs\/([^/]+)(?:\/(sources|cancel|resume|drafts\/([^/]+)(?:\/(simulate|commit|regenerate))?))?$/);
    if(agentMatch) {const job=agentJobs.find(item=>item.id===agentMatch[1]);if(!job)return reject(res,'合成Agent任务不存在',404);if(agentMatch[2]==='sources')return send(res,{...sources,world_id:job.world_id,world_title:job.world_title,sources:job.world_id===worlds[0].id?sources.sources:[]});if(method==='GET'){const frozen=clone(job);if(state.holdAgentRead){state.holdAgentRead=false;await new Promise(release=>state.pendingAgentReads.push({jobId:job.id,release}));}return send(res,frozen);}const value=await body(req);record(req,path,value);if(agentMatch[2]==='cancel'||agentMatch[2]==='resume'){job.status=agentMatch[2]==='cancel'?'cancelled':'review';return send(res,job);}const draft=job.drafts.find(item=>item.id===agentMatch[3]);if(!draft)return reject(res,'合成Agent草稿不存在',404);if(agentMatch[4]==='simulate'){draft.simulation=clone(simulation);return send(res,simulation);}if(agentMatch[4]==='regenerate')return send(res,job);assert.equal(value.expected_revision,draft.revision);if(state.failDraftSave)return reject(res,'合成Agent保存失败');if(agentMatch[4]==='commit'){if(state.failCommit)return reject(res,'合成Agent入库失败');const book={...clone(designBooks[0]),id:`agent-book-${designBooks.length}`,name:job.new_lorebook_name,entries:[clone(draft.payload)],revision:1};designBooks.push(book);draft.status='committed';draft.committed_book_id=book.id;return send(res,{book,draft});}Object.assign(draft,value,{revision:draft.revision+1,edited:true});return send(res,draft);}
    if(path==='/api/v1/bundle/export-selected/preview' && method==='POST'){const value=await body(req);record(req,path,value);return send(res,{items:[...(value.characters||[]).map(ref=>({kind:'character',id:ref.id,title:characters.find(item=>item.id===ref.id)?.card.name||ref.id,revision:ref.expected_revision,dependency:false})),...(value.lorebooks||[]).map(ref=>({kind:'lorebook',id:ref.id,title:designBooks.find(item=>item.id===ref.id)?.name||ref.id,revision:ref.expected_revision,dependency:false}))],notices:['只导出合成素材，私密故事不在此验收中。'],avatars:0,exclusions:{author_entries:0,provenance_entries:0}});}
    if(path==='/api/v1/bundle/export-selected' && method==='POST'){const value=await body(req);record(req,path,value);res.writeHead(200,{'content-type':'application/zip','content-disposition':'attachment; filename=synthetic.zip'});res.end(Buffer.from('Synthetic export boundary only'));return true;}
    return false;
  }
  return { route, state, releaseAgentReads:()=>{for(const item of state.pendingAgentReads.splice(0))item.release();}, books:designBooks, owners, worlds, worldDetail, archive, scenarios, inspirationJobs, importJobs, agentJobs, card };
}
