import { api } from '../../api/client';
import type { Api } from '../../api/Api';
/** Public stories endpoint surface. */
export const storiesClient: Pick<Api, 'addStoryParticipant' | 'createBookmark' | 'createGroup' | 'createScenario' | 'createSession' | 'createStoryEvent' | 'deleteBookmark' | 'deleteScenario' | 'deleteStoryEvent' | 'draftGroup' | 'forkBranch' | 'forkSave' | 'getBranchPoint' | 'getModelRequest' | 'getScenario' | 'getSessionSetup' | 'getStoryBackupStatus' | 'getStoryView' | 'getWorld' | 'getWorldline' | 'importScenario' | 'leaveGroup' | 'listGroupSources' | 'listGroups' | 'listMemories' | 'listScenes' | 'patchSceneImage' | 'listStoryBookmarks' | 'listStoryTrash' | 'listWorldOwners' | 'listWorlds' | 'memorySources' | 'memoryWindows' | 'patchBookmark' | 'patchBranch' | 'patchGroup' | 'patchNarrative' | 'patchSessionOptions' | 'patchSessionSetup' | 'purgeStory' | 'rememberEvent' | 'replyGroup' | 'saveScenarioWorld' | 'searchStory' | 'setStoryPromptPreset' | 'startScenario' | 'synthesizeSpeech' | 'updateMemory' | 'updateStoryEvent'> = {
  addStoryParticipant: api.addStoryParticipant,
  createBookmark: api.createBookmark,
  createGroup: api.createGroup,
  createScenario: api.createScenario,
  createSession: api.createSession,
  createStoryEvent: api.createStoryEvent,
  deleteBookmark: api.deleteBookmark,
  deleteScenario: api.deleteScenario,
  deleteStoryEvent: api.deleteStoryEvent,
  draftGroup: api.draftGroup,
  forkBranch: api.forkBranch,
  forkSave: api.forkSave,
  getBranchPoint: api.getBranchPoint,
  getModelRequest: api.getModelRequest,
  getScenario: api.getScenario,
  getSessionSetup: api.getSessionSetup,
  getStoryBackupStatus: api.getStoryBackupStatus,
  getStoryView: api.getStoryView,
  getWorld: api.getWorld,
  getWorldline: api.getWorldline,
  importScenario: api.importScenario,
  leaveGroup: api.leaveGroup,
  listGroupSources: api.listGroupSources,
  listGroups: api.listGroups,
  listMemories: api.listMemories,
  listScenes: api.listScenes,
  patchSceneImage: api.patchSceneImage,
  listStoryBookmarks: api.listStoryBookmarks,
  listStoryTrash: api.listStoryTrash,
  listWorldOwners: api.listWorldOwners,
  listWorlds: api.listWorlds,
  memorySources: api.memorySources,
  memoryWindows: api.memoryWindows,
  patchBookmark: api.patchBookmark,
  patchBranch: api.patchBranch,
  patchGroup: api.patchGroup,
  patchNarrative: api.patchNarrative,
  patchSessionOptions: api.patchSessionOptions,
  patchSessionSetup: api.patchSessionSetup,
  purgeStory: api.purgeStory,
  rememberEvent: api.rememberEvent,
  replyGroup: api.replyGroup,
  saveScenarioWorld: api.saveScenarioWorld,
  searchStory: api.searchStory,
  setStoryPromptPreset: api.setStoryPromptPreset,
  startScenario: api.startScenario,
  synthesizeSpeech: api.synthesizeSpeech,
  updateMemory: api.updateMemory,
  updateStoryEvent: api.updateStoryEvent,
};
