"""Generate transport types from backend response models; --check never writes."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from pydantic.json_schema import models_json_schema
from mrp.contracts.story import StoryView, SessionSetup, MessagePage, CommandResult, ApiError, BranchSummary, STORY_EVENT_TYPES
from mrp.contracts.commands import COMMAND_MODELS


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        props = [f'{json.dumps(key)}{"" if key in required else "?"}: {ts_type(value)};'
                 for key, value in schema.get("properties", {}).items()]
        extra = schema.get("additionalProperties")
        if extra:
            props.append(f"[key: string]: {ts_type(extra) if isinstance(extra, dict) else 'unknown'};")
        return "{ " + " ".join(props) + " }" if props else "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generated():
    _, schema = models_json_schema([(model, "serialization") for model in (
        StoryView, SessionSetup, MessagePage, CommandResult, ApiError, BranchSummary, *COMMAND_MODELS)])
    definitions = schema["$defs"]
    lines = ["// Generated by tools/maintenance/generate_story_contracts.py. Do not edit."]
    lines.append("export const STORY_EVENT_TYPES = " + json.dumps(STORY_EVENT_TYPES) + " as const;")
    lines.extend(f"export type {name} = {ts_type(value)};" for name, value in sorted(definitions.items()))
    return {"story-contracts.ts": "\n".join(lines) + "\n",
            "story-schema.json": json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = ROOT / "src/web/src/api/generated"
    for name, content in generated().items():
        path = destination / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Contract drift: regenerate {path.relative_to(ROOT)}")
        else:
            destination.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    print("Story contracts match." if args.check else "Story contracts generated.")


if __name__ == "__main__":
    main()
