import { forwardRef } from "react";
import type { Icon as PhosphorIcon, IconProps as PhosphorProps } from "@phosphor-icons/react";
import { BookOpenIcon as BookOpenGlyph } from "@phosphor-icons/react/dist/csr/BookOpen";
import { BooksIcon as LibraryBigGlyph } from "@phosphor-icons/react/dist/csr/Books";
import { UsersIcon as UsersGlyph } from "@phosphor-icons/react/dist/csr/Users";
import { GlobeHemisphereWestIcon as Globe2Glyph } from "@phosphor-icons/react/dist/csr/GlobeHemisphereWest";
import { PenNibIcon as PenToolGlyph } from "@phosphor-icons/react/dist/csr/PenNib";
import { SlidersHorizontalIcon as Settings2Glyph } from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
import { ChatCircleIcon as MessageCircleGlyph } from "@phosphor-icons/react/dist/csr/ChatCircle";
import { ListIcon as MenuGlyph } from "@phosphor-icons/react/dist/csr/List";
import { XIcon as XGlyph } from "@phosphor-icons/react/dist/csr/X";
import { ArrowLeftIcon as ArrowLeftGlyph } from "@phosphor-icons/react/dist/csr/ArrowLeft";
import { ArrowRightIcon as ArrowRightGlyph } from "@phosphor-icons/react/dist/csr/ArrowRight";
import { ArrowUpIcon as ArrowUpGlyph } from "@phosphor-icons/react/dist/csr/ArrowUp";
import { ArrowDownIcon as ArrowDownGlyph } from "@phosphor-icons/react/dist/csr/ArrowDown";
import { CaretDownIcon as ChevronDownGlyph } from "@phosphor-icons/react/dist/csr/CaretDown";
import { CaretUpIcon as ChevronUpGlyph } from "@phosphor-icons/react/dist/csr/CaretUp";
import { CaretLeftIcon as ChevronLeftGlyph } from "@phosphor-icons/react/dist/csr/CaretLeft";
import { CaretRightIcon as ChevronRightGlyph } from "@phosphor-icons/react/dist/csr/CaretRight";
import { DotsThreeIcon as MoreHorizontalGlyph } from "@phosphor-icons/react/dist/csr/DotsThree";
import { MagnifyingGlassIcon as SearchGlyph } from "@phosphor-icons/react/dist/csr/MagnifyingGlass";
import { PlusIcon as PlusGlyph } from "@phosphor-icons/react/dist/csr/Plus";
import { MinusIcon as MinusGlyph } from "@phosphor-icons/react/dist/csr/Minus";
import { CheckIcon as CheckGlyph } from "@phosphor-icons/react/dist/csr/Check";
import { UploadSimpleIcon as UploadGlyph } from "@phosphor-icons/react/dist/csr/UploadSimple";
import { DownloadSimpleIcon as DownloadGlyph } from "@phosphor-icons/react/dist/csr/DownloadSimple";
import { FileTextIcon as FileTextGlyph } from "@phosphor-icons/react/dist/csr/FileText";
import { ImageIcon as ImageGlyph } from "@phosphor-icons/react/dist/csr/Image";
import { SunIcon as SunGlyph } from "@phosphor-icons/react/dist/csr/Sun";
import { MoonStarsIcon as MoonGlyph } from "@phosphor-icons/react/dist/csr/MoonStars";
import { GitBranchIcon as GitBranchGlyph } from "@phosphor-icons/react/dist/csr/GitBranch";
import { InfoIcon as InfoGlyph } from "@phosphor-icons/react/dist/csr/Info";
import { PushPinIcon as PinGlyph } from "@phosphor-icons/react/dist/csr/PushPin";
import { SparkleIcon as SparklesGlyph } from "@phosphor-icons/react/dist/csr/Sparkle";
import { BrainIcon as BrainGlyph } from "@phosphor-icons/react/dist/csr/Brain";
import { FilmSlateIcon as ClapperboardGlyph } from "@phosphor-icons/react/dist/csr/FilmSlate";
import { BookmarkSimpleIcon as BookmarkGlyph } from "@phosphor-icons/react/dist/csr/BookmarkSimple";
import { ClipboardIcon as ClipboardGlyph } from "@phosphor-icons/react/dist/csr/Clipboard";
import { WaveformIcon as AudioLinesGlyph } from "@phosphor-icons/react/dist/csr/Waveform";
import { SpinnerGapIcon as LoaderCircleGlyph } from "@phosphor-icons/react/dist/csr/SpinnerGap";
import { SpeakerHighIcon as Volume2Glyph } from "@phosphor-icons/react/dist/csr/SpeakerHigh";
import { PencilSimpleIcon as PencilGlyph } from "@phosphor-icons/react/dist/csr/PencilSimple";
import { TrashIcon as Trash2Glyph } from "@phosphor-icons/react/dist/csr/Trash";
import { ArrowClockwiseIcon as RefreshCwGlyph } from "@phosphor-icons/react/dist/csr/ArrowClockwise";
import { EyeIcon as EyeGlyph } from "@phosphor-icons/react/dist/csr/Eye";
import { EyeSlashIcon as EyeOffGlyph } from "@phosphor-icons/react/dist/csr/EyeSlash";
import { PaperPlaneTiltIcon as SendGlyph } from "@phosphor-icons/react/dist/csr/PaperPlaneTilt";
import { WarningCircleIcon as AlertCircleGlyph } from "@phosphor-icons/react/dist/csr/WarningCircle";
import { FloppyDiskIcon as SaveGlyph } from "@phosphor-icons/react/dist/csr/FloppyDisk";
import { CheckCircleIcon as CheckCircle2Glyph } from "@phosphor-icons/react/dist/csr/CheckCircle";
import { CopyIcon as CopyGlyph } from "@phosphor-icons/react/dist/csr/Copy";
import { ArrowSquareOutIcon as ExternalLinkGlyph } from "@phosphor-icons/react/dist/csr/ArrowSquareOut";
import { ArrowCounterClockwiseIcon as RotateCcwGlyph } from "@phosphor-icons/react/dist/csr/ArrowCounterClockwise";
import { QuestionIcon as CircleHelpGlyph } from "@phosphor-icons/react/dist/csr/Question";
import { FolderOpenIcon as FolderOpenGlyph } from "@phosphor-icons/react/dist/csr/FolderOpen";

/** One regular-weight family. Semantic aliases keep UI call sites independent of the vendor. */
export type IconProps = Omit<PhosphorProps, "weight">;
function semanticIcon(Glyph: PhosphorIcon) {
  return forwardRef<SVGSVGElement, IconProps>(function InterfaceIcon({ size = 20, strokeWidth: _legacyStrokeWidth, ...props }, ref) {
    return <Glyph ref={ref} size={size} weight="regular" aria-hidden={props["aria-label"] ? undefined : true} {...props} />;
  });
}

export const BookOpen = /* @__PURE__ */ semanticIcon(BookOpenGlyph);
export const LibraryBig = /* @__PURE__ */ semanticIcon(LibraryBigGlyph);
export const Users = /* @__PURE__ */ semanticIcon(UsersGlyph);
export const Globe2 = /* @__PURE__ */ semanticIcon(Globe2Glyph);
export const PenTool = /* @__PURE__ */ semanticIcon(PenToolGlyph);
export const Settings2 = /* @__PURE__ */ semanticIcon(Settings2Glyph);
export const MessageCircle = /* @__PURE__ */ semanticIcon(MessageCircleGlyph);
export const Menu = /* @__PURE__ */ semanticIcon(MenuGlyph);
export const X = /* @__PURE__ */ semanticIcon(XGlyph);
export const ArrowLeft = /* @__PURE__ */ semanticIcon(ArrowLeftGlyph);
export const ArrowRight = /* @__PURE__ */ semanticIcon(ArrowRightGlyph);
export const ArrowUp = /* @__PURE__ */ semanticIcon(ArrowUpGlyph);
export const ArrowDown = /* @__PURE__ */ semanticIcon(ArrowDownGlyph);
export const ChevronDown = /* @__PURE__ */ semanticIcon(ChevronDownGlyph);
export const ChevronUp = /* @__PURE__ */ semanticIcon(ChevronUpGlyph);
export const ChevronLeft = /* @__PURE__ */ semanticIcon(ChevronLeftGlyph);
export const ChevronRight = /* @__PURE__ */ semanticIcon(ChevronRightGlyph);
export const MoreHorizontal = /* @__PURE__ */ semanticIcon(MoreHorizontalGlyph);
export const Search = /* @__PURE__ */ semanticIcon(SearchGlyph);
export const Plus = /* @__PURE__ */ semanticIcon(PlusGlyph);
export const Minus = /* @__PURE__ */ semanticIcon(MinusGlyph);
export const Check = /* @__PURE__ */ semanticIcon(CheckGlyph);
export const Upload = /* @__PURE__ */ semanticIcon(UploadGlyph);
export const Download = /* @__PURE__ */ semanticIcon(DownloadGlyph);
export const FileText = /* @__PURE__ */ semanticIcon(FileTextGlyph);
export const Image = /* @__PURE__ */ semanticIcon(ImageGlyph);
export const Sun = /* @__PURE__ */ semanticIcon(SunGlyph);
export const Moon = /* @__PURE__ */ semanticIcon(MoonGlyph);
export const GitBranch = /* @__PURE__ */ semanticIcon(GitBranchGlyph);
export const Info = /* @__PURE__ */ semanticIcon(InfoGlyph);
export const Pin = /* @__PURE__ */ semanticIcon(PinGlyph);
export const Sparkles = /* @__PURE__ */ semanticIcon(SparklesGlyph);
export const Brain = /* @__PURE__ */ semanticIcon(BrainGlyph);
export const Clapperboard = /* @__PURE__ */ semanticIcon(ClapperboardGlyph);
export const Bookmark = /* @__PURE__ */ semanticIcon(BookmarkGlyph);
export const Clipboard = /* @__PURE__ */ semanticIcon(ClipboardGlyph);
export const AudioLines = /* @__PURE__ */ semanticIcon(AudioLinesGlyph);
export const LoaderCircle = /* @__PURE__ */ semanticIcon(LoaderCircleGlyph);
export const Volume2 = /* @__PURE__ */ semanticIcon(Volume2Glyph);
export const Pencil = /* @__PURE__ */ semanticIcon(PencilGlyph);
export const Trash2 = /* @__PURE__ */ semanticIcon(Trash2Glyph);
export const RefreshCw = /* @__PURE__ */ semanticIcon(RefreshCwGlyph);
export const Eye = /* @__PURE__ */ semanticIcon(EyeGlyph);
export const EyeOff = /* @__PURE__ */ semanticIcon(EyeOffGlyph);
export const Send = /* @__PURE__ */ semanticIcon(SendGlyph);
export const AlertCircle = /* @__PURE__ */ semanticIcon(AlertCircleGlyph);
export const Save = /* @__PURE__ */ semanticIcon(SaveGlyph);
export const CheckCircle2 = /* @__PURE__ */ semanticIcon(CheckCircle2Glyph);
export const Copy = /* @__PURE__ */ semanticIcon(CopyGlyph);
export const ExternalLink = /* @__PURE__ */ semanticIcon(ExternalLinkGlyph);
export const RotateCcw = /* @__PURE__ */ semanticIcon(RotateCcwGlyph);
export const CircleHelp = /* @__PURE__ */ semanticIcon(CircleHelpGlyph);
export const FolderOpen = /* @__PURE__ */ semanticIcon(FolderOpenGlyph);
